"""empty message

Revision ID: 7da5268ab62a
Revises: ca29be774d78
Create Date: 2018-07-31 13:16:29.696510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da5268ab62a'
down_revision = 'ca29be774d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_token')
    # ### end Alembic commands ###
